services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:8080/tcp"
    volumes:
      - ./docker/adguard/work:/opt/adguardhome/work
      - ./docker/adguard/conf:/opt/adguardhome/conf
    networks:
      - webnet

  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptimekuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./docker/uptime-kuma/data:/app/data
    networks:
      - webnet

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./docker/caddy/data:/data
      - ./docker/caddy/config:/config
    networks:
      - webnet

networks:
  webnet:
    driver: bridge